# Generated by Django 5.1.3 on 2024-11-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='writer',
            new_name='author',
        ),
    ]
