# Generated by Django 5.1.3 on 2024-11-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_writer_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='contacts',
        ),
    ]
