# Generated by Django 5.1.3 on 2024-11-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_assignment_ans_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Delivery_Deadline',
            new_name='delivery_deadline',
        ),
    ]
