# Generated by Django 5.1.3 on 2024-11-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_delivery_deadline_assignment_delivery_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans_assignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='account.assignment'),
        ),
    ]
