# Generated by Django 5.1.3 on 2024-12-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_ans_assignment_student_alter_student_meli_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='meli_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='meli_code',
            field=models.CharField(max_length=10),
        ),
    ]
