# Generated by Django 5.1.3 on 2024-12-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_student_meli_code_alter_teacher_meli_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.DeleteModel(
            name='Ans_assignment',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
