version: '3.8'

services:
  web:
    build:
      context: .
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_NAME=school
      - DB_USER=school_admin
      - DB_PASSWORD=adminadmin
      - DB_HOST=db 
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=school_admin
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=school
    ports:
      - "5433:5432"

volumes:
  taskeschol_postgres_data: